# Encoding: utf-8

name 'phpstack'
maintainer 'Rackspace UK, Ltd.'
maintainer_email 'rackspace-cookbooks@rackspace.com'
license 'Apache 2.0'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
description 'Provides a full php stack'

version '0.0.3'

depends 'apt'
depends 'mysql'
depends 'database'
depends 'chef-sugar'
depends 'elasticsearch'
depends 'apache2', '~> 1.10'
depends 'memcached'
depends 'openssl'
depends 'redisio'
depends 'varnish'
depends 'rackspace_gluster'
depends 'platformstack'
depends 'mongodb'
depends 'build-essential'
depends 'java'
depends 'yum'
depends 'application_php'
depends 'application'
depends 'git'
depends 'php'
depends 'php-fpm'
depends 'mysql-multi'
